name: iOS Build Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest  # Esto le dice a GitHub que use un servidor Mac
    defaults:
      run:
        working-directory: KotlinProject
  
    steps:
      - uses: actions/checkout@v4
     
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # Este comando compila el framework de iOS
      - name: Build iOS Framework
        run: ./gradlew :composeApp:assembleDebugAppleFrameworkForXcode --stacktrace --info

      # Opcional: Si quieres generar el archivo para Appetize.io
      - name: Build Simulator App
        run: ./gradlew :composeApp:iosSimulatorArm64Binaries
